export const CERTIFICATES_LIST_REQUEST = 'CERTIFICATES_LIST_REQUEST';
export const CERTIFICATES_LIST_SUCCESS = 'CERTIFICATES_LIST_SUCCESS';
export const CERTIFICATES_LIST_FAIL = 'CERTIFICATES_LIST_FAIL';

export const CERTIFICATES_DETAILS_REQUEST = 'CERTIFICATES_DETAILS_REQUEST';
export const CERTIFICATES_DETAILS_SUCCESS = 'CERTIFICATES_DETAILS_SUCCESS';
export const CERTIFICATES_DETAILS_FAIL = 'CERTIFICATES_DETAILS_FAIL';