export const CHAPTER_LIST_REQUEST = 'CHAPTER_LIST_REQUEST';
export const CHAPTER_LIST_SUCCESS = 'CHAPTER_LIST_SUCCESS';
export const CHAPTER_LIST_FAIL = 'CHAPTER_LIST_FAIL';

export const CHAPTER_DETAILS_REQUEST = 'CHAPTER_DETAILS_REQUEST';
export const CHAPTER_DETAILS_SUCCESS = 'CHAPTER_DETAILS_SUCCESS';
export const CHAPTER_DETAILS_FAIL = 'CHAPTER_DETAILS_FAIL';