
export const LESSONS_LIST_REQUEST = 'LESSONS_LIST_REQUEST';
export const LESSONS_LIST_SUCCESS = 'LESSONS_LIST_SUCCESS';
export const LESSONS_LIST_FAIL = 'LESSONS_LIST_FAIL';


export const LESSON_DETAILS_REQUEST = 'LESSONS_DETAIL_REQUEST';
export const LESSON_DETAILS_SUCCESS = 'LESSONS_DETAIL_SUCCESS';
export const LESSON_DETAILS_FAIL = 'LESSONS_DETAIL_FAIL';