
export const LESSONS_LIST_REQUEST = 'LESSONS_LIST_REQUEST';
export const LESSONS_LIST_SUCCESS = 'LESSONS_LIST_SUCCESS';
export const LESSONS_LIST_FAIL = 'LESSONS_LIST_FAIL';


export const LESSONS_DETAILS_REQUEST = 'LESSONS_DETAILS_REQUEST';
export const LESSONS_DETAILS_SUCCESS = 'LESSONS_DETAILS_SUCCESS';
export const LESSONS_DETAILS_FAIL = 'LESSONS_DETAILS_FAIL';