export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const UPDATE_BILLING_ADDRESS_REQUEST = 'UPDATE_BILLING_ADDRESS_REQUEST'
export const UPDATE_BILLING_ADDRESS_SUCCESS = 'UPDATE_BILLING_ADDRESS_SUCCESS'
export const UPDATE_BILLING_ADDRESS_FAIL = 'UPDATE_BILLING_ADDRESS_FAIL'

export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST' 
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS' 
export const APPLY_COUPON_FAIL = 'APPLY_COUPON_FAIL' 

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST' 
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS' 
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL' 
