export const REGISTERED_COURSE_LIST_REQUEST = 'REGISTERED_COURSE_LIST_REQUEST';
export const REGISTERED_COURSE_LIST_SUCCESS = 'REGISTERED_COURSE_LIST_SUCCESS';
export const REGISTERED_COURSE_LIST_FAIL = 'REGISTERED_COURSE_LIST_FAIL';

export const REGISTERED_COURSE_DETAILS_REQUEST = 'REGISTERED_COURSE_DETAILS_REQUEST';
export const REGISTERED_COURSE_DETAILS_SUCCESS = 'REGISTERED_COURSE_DETAILS_SUCCESS';
export const REGISTERED_COURSE_DETAILS_FAIL = 'REGISTERED_COURSE_DETAILS_FAIL';


export const IS_REGISTERED_COURSE_FAIL = 'IS_REGISTERED_COURSE_FAIL'
export const IS_REGISTERED_COURSE_SUCCESS = 'IS_REGISTERED_COURSE_SUCCESS'
export const IS_REGISTERED_COURSE_REQUEST = 'IS_REGISTERED_COURSE_REQUEST'