
export const WEBINARS_LIST_REQUEST = 'WEBINARS_LIST_REQUEST';
export const WEBINARS_LIST_SUCCESS = 'WEBINARS_LIST_SUCCESS';
export const WEBINARS_LIST_FAIL = 'WEBINARS_LIST_FAIL';


export const WEBINARS_DETAILS_REQUEST = 'WEBINARS_DETAILS_REQUEST';
export const WEBINARS_DETAILS_SUCCESS = 'WEBINARS_DETAILS_SUCCESS';
export const WEBINARS_DETAILS_FAIL = 'WEBINARS_DETAILS_FAIL';